# Generated by Django 5.2.7 on 2025-10-17 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=100)),
                ('archive_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('downloaded', 'Downloaded')], default='uploaded', max_length=20)),
                ('compression_quality', models.IntegerField(blank=True, null=True)),
                ('compression_max_dimension', models.IntegerField(blank=True, null=True)),
                ('compression_no_resize', models.BooleanField(default=False)),
                ('files_count', models.IntegerField(default=0)),
                ('files_successful', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('total_original_mb', models.FloatField(default=0)),
                ('total_compressed_mb', models.FloatField(default=0)),
                ('savings_percent', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compression_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compression Session',
                'verbose_name_plural': 'Compression Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompressionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('output_name', models.CharField(max_length=255)),
                ('original_size_mb', models.FloatField()),
                ('compressed_size_mb', models.FloatField()),
                ('savings_percent', models.FloatField()),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compressor.compressionsession')),
            ],
            options={
                'ordering': ['original_name'],
            },
        ),
    ]
